### ISSUE TITLE
Readme.md file can be more interactive and fascinating 

### ISSUE THREAD

**Issue by Meetjain1** [jaibhedia/VoteChain#21]
Hello @jaibhedia I am working under gssoc24 , I can make readme.md file of Votechain more interactive by adding images and applying some styles , please assign this issue to me Thankyou.

**Comment by jaibhedia** [comment]
@Meetjain1 I have assigned you this issue, please start working on it.

**Comment by Meetjain1** [comment]
@jaibhedia sure sir

**Comment by technicalkuldeep** [comment]
**Hii Sir , I have good expertise in HTML , CSS , JavaScript , Python 
I want to work in your project and want to resolve this issue 
So I request you to please assign me this issue .**

**Comment by Meetjain1** [comment]
Since the Pr #34 is merged related to this issue , so I am closing this issue . Thankyou
