### ISSUE TITLE
CODE_OF_CONDUCT.md fle is missing

### ISSUE THREAD

**Issue by Meetjain1** [jaibhedia/VoteChain#35]
@jaibhedia sir , CODE_OF_CONDUCT.md file is missing in our repository still , Please assign this issue to me I will add it . Thankyou

**Comment by aasthakourav20** [comment]
We recommend that every repo has a code of conduct. If you don’t feel comfortable creating your own Code of Conduct from scratch we highly recommend using one of the templates provided by GitHub. If you do use a template, please read through the template and ensure that you can and will abide by the Code of Conduct.

Please follow these instructions on how to add a Code of Conduct.

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

Kindly assign this task to me under GSSoC'24

**Comment by jaibhedia** [comment]
It's already been taken care of, thank you.

**Comment by Meetjain1** [comment]
@jaibhedia ok sir
